version: '3'
services:
  web:
    image: odoo:latest
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - /home/dam2a/Escritorio/odoo/srv/odoo:/var/lib/odoo
      - /home/dam2a/Escritorio/odoo/srv/odoo/config:/etc/odoo
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgresjira
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    ports:
      - "5432:5432"
    volumes:
      - /home/dam2a/Escritorio/odoo/sql:/var/lib/postgresql/data
